apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: infisical-csi-provider
  name: infisical-csi-provider
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: infisical-csi-provider
  template:
    metadata:
      labels:
        app: infisical-csi-provider
    spec:
      tolerations:
      containers:
        - name: infisical-csi-provider
          image: infisical-csi-provider:latest
          imagePullPolicy: Never
          args:
            - -endpoint=/provider/infisical.sock
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - name: providervol
              mountPath: "/provider"
          livenessProbe:
            httpGet:
              path: "/health/ready"
              port: 8080
              scheme: "HTTP"
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: "/health/ready"
              port: 8080
              scheme: "HTTP"
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-infisical-csi-provider
spec:
  provider: infisical
  secretObjects:
    - data:
        - key: username
          objectName: imanother
      secretName: foosecret
      type: Opaque
  parameters:
    infisicalUrl: "http://host.minikube.internal:8080"
    identityId: "ad2f8c67-cbe2-417a-b5eb-1339776ec0b3"
    projectId: "09eda1f8-85a3-47a9-8a6f-e27f133b2a36"
    envSlug: "dev"
    secrets: |
      - secretPath: "/engineering"
        fileName: "test"
        secretKey: "SSSSS"
      - secretPath: "/"
        fileName: "imanother"
        secretKey: "IMANOTHERTEZ"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-store
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "my-infisical-csi-provider"
