name: Release Docker image for Infisical CSI provider
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔧 Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🐋 Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: |
            infisical/infisical-csi-provider:latest
            infisical/infisical-csi-provider:${{ github.ref_name }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install python
        uses: actions/setup-python@v4

      - name: Install Cloudsmith CLI
        run: pip install --upgrade cloudsmith-cli

      - name: Build and push helm package to Cloudsmith
        run: sh upload-to-cloudsmith.sh
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
